server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /demo
spring:
#  datasource:
#    platform: h2
#    schema: classpath:db/schema.sql
#    data: classpath:db/data.sql
#    sql-script-encoding: utf-8
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: sa
#    initialization-mode: always
#    continue-on-error: true
#    hikari:
#      maximum-pool-size: 8
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/shardingjdbc?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&tinyInt1isBit=false
#    username: root
#    password: admin123
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss


###### shardingJDBC ##########
  shardingsphere:
    datasource:
      names: ds
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/shardingjdbc?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&tinyInt1isBit=false
        username: root
        password: admin123
    sharding:
      tables:
        t_order:
          actual-data-nodes: ds.t_order_$->{2020..2021}_$->{1..12}
          table-strategy:
            standard:
              sharding-column: create_time
              precise-algorithm-class-name: io.ian.demo.core.shardingjdbc.DatePreciseShardingAlgorithm
              range-algorithm-class-name: io.ian.demo.core.shardingjdbc.DateRangeShardingAlgorithm
        t_order_item:
          actual-data-nodes: ds.t_order_item_$->{2020..2021}_$->{1..12}
          table-strategy:
            standard:
              sharding-column: order_create_time
              precise-algorithm-class-name: io.ian.demo.core.shardingjdbc.DatePreciseShardingAlgorithm
              range-algorithm-class-name: io.ian.demo.core.shardingjdbc.DateRangeShardingAlgorithm
      binding-tables:
        - t_order,t_order_item
      defaultDataSourceName: ds
    props:
      sql:
        show: true
###### shardingJDBC ##########

#mybatis
mybatis-plus:
  mapper-locations: classpath*:io/ian/demo/service/mapping/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: io.ian.demo.service.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置
    #    logic-delete-value: 1
    #    logic-not-delete-value: 0
    #    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    meta-object-handler: io.ian.demo.web.handler.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true


